name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    job_one:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
          - name: Deploying server ssh connection
            uses: appleboy/ssh-action@master
            with:
                host: ${{secrets.SERVER_URL}}
                key: ${{secrets.SSH_PRIVATE_KEY}}
                username: root
                port: 22
                script: |
                    cd MineSweeperWeb
                    git pull
                    git status
                    systemcl stop kestrel-helloapp.service
                    dotnet publish -o ../publish
                    systemcl start kestrel-helloapp.service